import Head from "next/head";
import { Inter } from "next/font/google";
import {
  Container,
  HStack,
  Heading,
  SimpleGrid,
  VStack,
} from "@chakra-ui/layout";

import BlogCard from "@/components/BlogCard";

import BlogDescs from "@/data/blogDescs";
import Teacher from "@/components/Teacher";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading textAlign="center" mb={6} mt={12}>
          Učitelský sbor LAMBDY
        </Heading>
        <HStack
          alignItems="flex-start"
          maxW="80vw"
          mx="auto"
          justify="center"
          my={6}
          gap={12}
        >
          <Teacher name="Radovan Milánek" title="ředitel školy" />
          <Teacher
            name="Usb. Jan Prodal, PhDr."
            title="učitel fyziky, programování, správce kódů pro odpálení nukleárních hlavic"
          />
          <Teacher
            name="akademický malíř El Greco"
            title="učitel grafiky, školní doktor"
          />
        </HStack>

        <Heading textAlign="center" mb={6} mt={12}>
          Blogísek ředitele Milánka
        </Heading>
        <HStack alignItems="flex-start" maxW="80vw" mx="auto" justify="center">
          <BlogCard
            heading="MHD Kacys pomohlo najít kluka z autobusu"
            image="https://www.delta-skola.cz/data/blog-posts/images/orig/dopravni-podnik.webp"
            text={BlogDescs.MHDkacys}
          />
          <BlogCard
            heading="Už nám nesmrdí umyvadlo"
            image="https://images.unsplash.com/photo-1584961503022-d19acee0af7b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=718&q=80"
            text={BlogDescs.Umyvadlo}
          />
          <BlogCard
            heading="Venda Sigsauer je prostě talent"
            image=""
            text={BlogDescs.Umyvadlo}
          />
        </HStack>
      </main>
    </>
  );
}
